config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    confirmations: "users/confirmations",
    passwords:     "users/passwords",
    registrations: "users/registrations",
    sessions:      "users/sessions"
  }
  
  root 'users#me'
  
  get 'users/id:id' => 'users#show', as: 'user'
  post 'users/login' => 'users#login'
  get 'users/id:id/about' => 'users#get_about'
  get 'users/id:id/login' => 'users#get_login'
  post 'users/about' => 'users#about'
  post 'avatar' => 'users#avatar', as: 'avatar', defaults: { format: 'js' }
  post 'users/id:id/follow' => 'users#follow'
  post 'users/id:id/unfollow' => 'users#unfollow'
  
  post 'posts/new_pic' => 'posts#create_pic_post', as: 'new_pic_post', defaults: { format: 'js' }
  post 'posts/new_video' => 'posts#create_video_post', as: 'new_video_post', defaults: { format: 'js' }
  get 'posts/id:id' => 'posts#show', as: 'post'
  get 'feed' => 'posts#feed', as: 'feed'
  post 'posts/id:id/like' => 'posts#like', as: 'like', defaults: { format: 'js' }
  post 'posts/id:id/dislike' => 'posts#dislike', as: 'dislike', defaults: { format: 'js' }
  
  post 'posts/id:id' => 'comments#create', as: 'new_comment', defaults: { format: 'js'}
  delete 'comments/id:id' => 'comments#destroy', as: 'comments'
  
  get 'search/quick' => 'search#quick', as: 'qsearch'
  get 'search/' => 'search#index', as: 'search'
  
  get 'follows' => 'users#follows', as: 'follows'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
  has_many :comments
  has_attached_file :avatar, styles: { medium: "150x150>", thumb: "70x70>" }, default_url: lambda { |image| ActionController::Base.helpers.asset_path("/assets/ava-:style.png")}
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
  acts_as_followable
  acts_as_follower
  acts_as_voter
  self.per_page = 10
  
  def self.quick_search(search)
  	if search
  		self.where("login like ?", "%#{search}%")
  	else
  		self.all
  	end
  end
  
  def self.search(login, about)
  	if login != ""
  		if about != ""
  		  self.where("login like ? AND about like ?", "%#{login}%", "%#{about}%")
  		else
  			self.where("login like ?", "%#{login}%")
  		end
  	elsif about != ""
  		self.where("about like ?", "%#{about}%")
  	else
  		self.all
  	end
  end

end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    login = Haikunator.haikunate
    params = sign_up_params
    params[:login] = login
    params[:about] = "Newable guy"
    build_resource(params)

    resource.save
    yield resource if block_given?
    if resource.persisted?
      if resource.active_for_authentication?
        set_flash_message :notice, :signed_up if is_flashing_format?
        sign_up(resource_name, resource)
        respond_with resource, location: after_sign_up_path_for(resource)
      else
        set_flash_message :notice, :"signed_up_but_#{resource.inactive_message}" if is_flashing_format?
        expire_data_after_sign_in!
        respond_with resource, location: after_inactive_sign_up_path_for(resource)
      end
    else
      clean_up_passwords resource
      set_minimum_password_length
      respond_with resource
    end
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :authenticate_user!
  skip_before_action :verify_authenticity_token, :only => [:avatar]
  
  def show
    @user=User.find(params[:id])
    @posts = @user.posts.paginate(:page => params[:page]).order('created_at DESC')
  end
  
  def me
    redirect_to current_user
  end
  
  def login
    login = params[:login]
    if request.xhr?
    	login = "Anonimous" if  login.tr(" \n\t", '') == ""
    	current_user.login = login
      current_user.save
      respond_to do |format|
        format.js {render file: 'users/login'}
      end
     end
  end
  
  def get_login
    if request.xhr?
    	user = User.find(params[:id])
      render :json => {
        login: user.login
      }
    end
  end
  
  def get_about
    if request.xhr?
    	user = User.find(params[:id])
      render :json => {
        about: user.about
      }
    end
  end
  
  def about
    about = params[:about]
    if request.xhr?
    	about = "Silent Bob" if  about.tr(" \n\t", '') == ""
    	current_user.about = about
      current_user.save
      respond_to do |format|
        format.js {render file: 'users/about'}
      end
    end
  end
  
  def avatar
    current_user.avatar = params[:avatar]
    current_user.save
    @user = current_user
    respond_to do |format|
      format.js
    end
  end
  
  def follow
  	user = User(params[:id])
  	current_user.follow(user)
  end
  
  def follow
  	if request.xhr?
  		user = User.find(params[:id])
  	  current_user.follow(user)
  	  respond_to do |format|
        format.js { render nothing: true } 
      end
  	end
  end
  
  def unfollow
  	if request.xhr?
  	  user = User.find(params[:id])
  	  current_user.stop_following(user)
  	  respond_to do |format|
        format.js { render nothing: true } 
      end
  	end
  end
  
  def follows
    @follows = current_user.follows_by_type('User').paginate(page: params[:page], per_page: 10).order('created_at DESC')
  end
end

app/views/users/_avatar-thumb.haml
= image_tag @user.avatar.url(:thumb) 

app/views/users/_avatar.haml
= image_tag @user.avatar.url(:medium), id: "image-avatar"

app/views/users/_follows_page.haml
= will_paginate @follows, id: 'pag1'
- flag = true
-@follows.each do |follow|
  - user = User.find(follow.followable_id)
  %div{class: "user-prev item-#{flag}"}
    = link_to user.login, user
  -flag = !flag 
= will_paginate @follows, id: 'pag2'

app/views/users/_index.haml
= will_paginate @users, id: 'pag1'
- flag = true
-@users.each do |user|
  %div{class: "user-prev item-#{flag}"}
    = link_to user.login, user
  -flag = !flag 
= will_paginate @users, id: 'pag2'
- if @users.length == 0
  %p No such users

app/views/users/_thumb.haml
= image_tag @user.avatar.url(:thumb) 

app/views/users/about.js.erb
var url = location.protocol + '//' + location.host + location.pathname + '/about';
$.ajax({
  type: "GET",
  url: url,
  dataType: "json",
  success: function(data) {
    $("#about-text").html(data.about);
    $("#about-form textarea").val(data.about);
  }
});
$(".changeable > #about-form").hide();
$(".changeable > #about-text").show();

app/views/users/avatar.js.erb
$('#avatar-image').html("<%= escape_javascript render("avatar") %>");
$('.ava-thumb').html("<%= escape_javascript render("thumb") %>");

app/views/users/follows.haml
.info-container
  %h1 Your follows:
  #follows
    =render 'follows_page'

app/views/users/follows.js.erb
$("#follows").html("<%= escape_javascript(render("follows_page")) %>");

app/views/users/login.js.erb
var url = location.protocol + '//' + location.host + location.pathname + '/login';
$.ajax({
  type: "GET",
  url: url,
  dataType: "json",
  success: function(data) {
    $("#login-text").html(data.login);
    $(".changeable #login").val(data.login);
  }
});
$(".changeable > #login-form").hide();
$(".changeable > #login-text").show();

app/views/users/show.haml
-if @user != current_user
  -if current_user.following?(@user)
    %span.unfollow −
  -else
    %span.follow +
.info-container
  -if @user == current_user
    .changeable
      = form_tag avatar_path, method: :path, remote: true, multipart: true  do |form|
        = file_field_tag :avatar, accept: 'image/png,image/gif,image/jpeg, image/jpg', id: "avatar"
        #avatar-image
          = image_tag @user.avatar.url(:medium)
        %br/
        = submit_tag "Change avatar", class: "button-default ava-submit"
      #login-text
        = @user.login
      = form_tag '/users/login', method: :path, remote: true, id: 'login-form' do |form|
        = text_field_tag :login, "", autocomplete: "off"
        %br/
        = submit_tag "Update login", class: "button-default"
      %br/
      %strong About:
      %br/
      %pre#about-text
      = form_tag '/users/about', method: :path, remote: true, id: 'about-form' do |form|
        = text_area_tag :about
        %br/
        = submit_tag "Update about", class: "button-default"
    = link_to "Your follows: #{@user.follows_by_type('User').length}", follows_path
    %br/
    = link_to "Your feed", feed_path
    %br/
    = link_to "Change reg. data", edit_user_registration_path
  -else
    = image_tag @user.avatar.url(:medium)
    %br/
    #login-text
    %br/
    %strong About:
    %br/
    %pre#about-text
-if @user == current_user
  .info-container
    #dowload-buttons-positioner
      #new-pic-button.download-button
        = image_tag(asset_path("picture.png"))
      #new-video-button.download-button
        = image_tag(asset_path("tool.png"))
    #new-pic.new-post
      = form_for PicPost.new(), url: new_pic_post_path, remote: true, multipart: true, method: :post do |form|
        = form.text_field :title, placeholder: "Title"
        %br/
        = form.file_field :image, class: "inputfile"
        = form.label :image
        = form.text_field :definition, placeholder: "definition"
        %br/
        = form.submit "Post", class: "button-default"
    #new-video.new-post
      = form_for VideoPost.new(), url: new_video_post_path, remote: true, multipart: true, method: :post do |form|
        = form.text_field :title, placeholder: "Title"
        %br/
        = form.text_field :link, placeholder: "Vimeo or Youtube link"
        %br/
        = form.text_field :definition, placeholder: "definition"
        %br/
        = form.submit "Post", class: "button-default"
    #error-post
      -if flash[:post_error]
        = flash[:post_error]
#posts
  = render 'posts/posts'

app/views/users/show.js.erb
$("#posts").html("<%= escape_javascript(render("posts/posts")) %>");