config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    confirmations: "users/confirmations",
    passwords:     "users/passwords",
    registrations: "users/registrations",
    sessions:      "users/sessions"
  }
  
  root 'users#me'
  
  get 'users/id:id' => 'users#show', as: 'user'
  post 'users/login' => 'users#login'
  get 'users/id:id/about' => 'users#get_about'
  get 'users/id:id/login' => 'users#get_login'
  post 'users/about' => 'users#about'
  post 'avatar' => 'users#avatar', as: 'avatar', defaults: { format: 'js' }
  post 'users/id:id/follow' => 'users#follow'
  post 'users/id:id/unfollow' => 'users#unfollow'
  
  post 'posts/new_pic' => 'posts#create_pic_post', as: 'new_pic_post', defaults: { format: 'js' }
  post 'posts/new_video' => 'posts#create_video_post', as: 'new_video_post', defaults: { format: 'js' }
  get 'posts/id:id' => 'posts#show', as: 'post'
  get 'feed' => 'posts#feed', as: 'feed'
  post 'posts/id:id/like' => 'posts#like', as: 'like', defaults: { format: 'js' }
  post 'posts/id:id/dislike' => 'posts#dislike', as: 'dislike', defaults: { format: 'js' }
  
  post 'posts/id:id' => 'comments#create', as: 'new_comment', defaults: { format: 'js'}
  delete 'comments/id:id' => 'comments#destroy', as: 'comments'
  
  get 'search/quick' => 'search#quick', as: 'qsearch'
  get 'search/' => 'search#index', as: 'search'
  
  get 'follows' => 'users#follows', as: 'follows'
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user
	has_one :pic_post
	has_one :video_post
	has_many :comments
	self.per_page = 10
	acts_as_votable
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  def create_pic_post
  	@post = Post.new
  	@post.user = current_user
    @pic_post = PicPost.new( pic_post_params)
    @user = current_user
    @posts = current_user.posts.paginate(:page => params[:page]).order('created_at DESC')
    if @pic_post.valid?
    	@post.save
      @pic_post.post = @post
      @pic_post.save
    else
    	if @pic_post.title.length < 1 || @pic_post.title.length > 200
    		flash.now[:post_error] = "The title cannot be fill or longer then 200 chars"
    	else
    		flash.now[:post_error] = "You should attach a picture to the post"
    	end
    end
    respond_to do |format|
      format.js {render file: '/posts/create_post.js.erb'}
    end
  end
  
  def create_video_post
  	@post = Post.new
  	@post.user = current_user
    @video_post = VideoPost.new(video_post_params)
    @user = current_user
    @posts = current_user.posts.paginate(:page => params[:page]).order('created_at DESC')
    if @video_post.valid?
    	@post.save
      @video_post.post = @post
      @video_post.save
    else
    	if @video_post.title.length < 1 || @video_post.title.length > 200
    		flash.now[:post_error] = "The title cannot be fill or longer then 200 chars"
    	else
    		flash.now[:post_error] = "You should attach a youtube or vimeo video to the post"
    	end
    end
    respond_to do |format|
      format.js {render file: '/posts/create_post.js.erb'}
    end
  end

  def destroy
  	@post = Post.find(params[:id])
    if @post.user == current_user
    	if @post.pic_post
    		@post.pic_post.destroy
    	end
    	if @post.video_post
    		@post.video_post.destroy
    	end
      @post.destroy
      if request.xhr?
      	render :json => {}
      else
      	respond_to do |format|
          format.html { redirect_to current_user, notice: 'Post was successfully destroyed.' }
        end
      end
    else
    	if request.xhr?
      	render :json => {}
      else
    	  redirect_to root_path
    	end
    end
  end
  
  def show
  	@post = Post.find(params[:id])
  	@comments = @post.comments.paginate(:page => params[:page]).order('created_at DESC')
  	@comment = Comment.new
  end
  
  def feed
    follows = current_user.all_follows
    posts = nil
    follows.each do |follow|
    	user = User.find(follow.followable_id)
    	if posts
    		posts = posts.union(Post.where(user_id: user.id))
      else
      	posts = Post.where(user_id: user.id)
      end
    end
    user = User.find(follows.first.followable_id)
  	@posts = posts.paginate(:page => params[:page]).order('created_at DESC')
  end
  
  def like
  	@post = Post.find(params[:id])
  	if current_user.voted_up_on? @post
  		@post.unliked_by current_user
  	else
  	  @post.liked_by current_user
  	end
  	respond_to do |format|
      format.js {render file: '/posts/likes.js.erb'}
    end
  end
  
  def dislike
  	@post = Post.find(params[:id])
  	if current_user.voted_down_on? @post
  		@post.undisliked_by current_user
  	else
  	  @post.disliked_by current_user
  	end
  	respond_to do |format|
      format.js {render file: '/posts/likes.js.erb'}
    end
  end

  private

  # Use strong_parameters for attribute whitelisting
  # Be sure to update your create() and update() controller methods.

  def pic_post_params
    params.require(:pic_post).permit(:title, :image, :definition).to_h
  end
  
  def video_post_params
    params.require(:video_post).permit(:title, :link, :definition).to_h
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_error.haml
-if flash[:error]
  #error
    %em.close ×
    = flash[:error]

app/views/posts/_like_menu.haml
-if current_user.voted_up_on? @post
  = link_to image_tag(asset_path("like.png")), like_path(@post)
-else
  = link_to image_tag(asset_path("like.png")), like_path(@post), class: 'like-inactive'
-if current_user.voted_down_on? @post
  = link_to image_tag(asset_path("dislike.png")), dislike_path(@post)
-else
  = link_to image_tag(asset_path("dislike.png")), dislike_path(@post), class: 'like-inactive'
%br/
= render 'posts/like_rate'

app/views/posts/_like_rate.haml
-if @post.get_likes.size - @post.get_dislikes.size > 0
  %span.liked Rate:
  %span.liked 
    = @post.get_likes.size - @post.get_dislikes.size
-elsif @post.get_likes.size - @post.get_dislikes.size < 0
  %span.disliked Rate:
  %span.disliked 
    = @post.get_likes.size - @post.get_dislikes.size
-else
  %span.like_rate Rate:
  %span.like_rate
    = @post.get_likes.size - @post.get_dislikes.size

app/views/posts/_posts.haml
= will_paginate @posts, id: 'pag1'
-for @post in @posts
  .post
    .ava-thumb
      = link_to(image_tag(@post.user.avatar.url(:thumb)), @post.user)
    .info-container
      -if @post.pic_post
        = link_to @post.pic_post.title, @post, class: "title"
        %br/
        = image_tag @post.pic_post.image.url(:medium)
        %br/
        -if @post.pic_post.definition != ""
          %pre
            = @post.pic_post.definition
          %br/
      -if @post.video_post
        - c = Conred::Video.new(video_url: @post.video_post.link, width: 285, height: 185,error_message: "Video url is invalid")
        = link_to @post.video_post.title, @post, class: "title"
        %br/
        = c.code.html_safe
        %br/
        -if @post.video_post.definition != ""
          %p 
            = @post.video_post.definition
          %br/
      %i
        = @post.created_at.to_formatted_s :db
      %br/
      -if @user == current_user
        %em.close{data: {id: @post.id}} ×
        = render 'posts/like_rate'
      -else 
        %div{class: "like_menu like_menu-#{@post.id}"}
          = render 'posts/like_menu'
= will_paginate @posts, id: 'pag2'

app/views/posts/create_pic_post.js.erb
$("#posts").html("<%= escape_javascript(render("users/posts")) %>");
pag = $("#pag1").html();
while (pag.search("posts/new_pic") != -1) {
  pag = pag.replace("posts/new_pic", "users/<%= @user.id %>");
}
$("#pag1").html(pag);
pag = $("#pag2").html();
while (pag.search("posts/new_pic") != -1) {
  pag = pag.replace("posts/new_pic", "users/<%= @user.id %>");
}
$("#pag2").html(pag);

app/views/posts/create_post.js.erb
$(".new-post").hide();
$("#posts").html("<%= escape_javascript(render("posts/posts")) %>");
pag = $("#pag1").html();
while (pag.search("posts/new_pic") != -1) {
  pag = pag.replace("posts/new_pic", "users/<%= @user.id %>");
}
$("#pag1").html(pag);
pag = $("#pag2").html();
while (pag.search("posts/new_pic") != -1) {
  pag = pag.replace("posts/new_pic", "users/<%= @user.id %>");
}
$("#pag2").html(pag);
  
<% if flash[:post_error] %>
  $('#error-post').html("<%= flash[:post_error] %>");
  setTimeout("$('#error-post').html('');", 5000);
<% end %>
  

app/views/posts/create_video_post.js.erb
$("#posts").html("<%= escape_javascript(render("users/posts")) %>");
pag = $("#pag1").html();
while (pag.search("posts/new_pic") != -1) {
  pag = pag.replace("posts/new_pic", "users/<%= @user.id %>");
}
$("#pag1").html(pag);
pag = $("#pag2").html();
while (pag.search("posts/new_pic") != -1) {
  pag = pag.replace("posts/new_pic", "users/<%= @user.id %>");
}
$("#pag2").html(pag);

app/views/posts/feed.haml
#posts
  = render 'posts'

app/views/posts/feed.js.erb
$("#posts").html("<%= escape_javascript(render("posts")) %>");

app/views/posts/likes.js.erb
$(".like_menu-<%= @post.id %>").html("<%= escape_javascript(render("posts/like_menu")) %>");

app/views/posts/show.haml
.post
  .ava-thumb
    = link_to(image_tag(@post.user.avatar.url(:thumb)), @post.user)
  .info-container
    -if @post.pic_post
      %h1.title<
        = @post.pic_post.title
      %br/
      = image_tag @post.pic_post.image.url(:medium)
      %br/
      -if @post.pic_post.definition != ""
        %pre 
          = @post.pic_post.definition
        %br/
    -if @post.video_post
      - c = Conred::Video.new(video_url: @post.video_post.link, width: 512, height: 288 ,error_message: "Video url is invalid")
      = link_to @post.video_post.title, @post, class: "title"
      %br/
      = c.code.html_safe
      %br/
      -if @post.video_post.definition != ""
        %pre 
          = @post.video_post.definition
        %br/
    -if @post.user == current_user
      = link_to 'Delete', @post, method: :delete
      = render 'posts/like_rate'
    -else
      %div{class: "like_menu like_menu-#{@post.id}"}
        = render 'like_menu'
      
.info-container
  = form_for @comment, url: post_path(@post), remote: true do |f|
    = f.text_area :text
    %br/
    =f.submit "Comment", class: 'button-default'
    
#comments
  = render 'comments/comments'

app/views/posts/show.js.erb
$("#comments").html("<%= escape_javascript(render("comments/comments")) %>");