config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    confirmations: "users/confirmations",
    passwords:     "users/passwords",
    registrations: "users/registrations",
    sessions:      "users/sessions"
  }
  
  root 'users#me'
  
  get 'users/id:id' => 'users#show', as: 'user'
  post 'users/login' => 'users#login'
  get 'users/id:id/about' => 'users#get_about'
  get 'users/id:id/login' => 'users#get_login'
  post 'users/about' => 'users#about'
  post 'avatar' => 'users#avatar', as: 'avatar', defaults: { format: 'js' }
  post 'users/id:id/follow' => 'users#follow'
  post 'users/id:id/unfollow' => 'users#unfollow'
  
  post 'posts/new_pic' => 'posts#create_pic_post', as: 'new_pic_post', defaults: { format: 'js' }
  post 'posts/new_video' => 'posts#create_video_post', as: 'new_video_post', defaults: { format: 'js' }
  get 'posts/id:id' => 'posts#show', as: 'post'
  get 'feed' => 'posts#feed', as: 'feed'
  post 'posts/id:id/like' => 'posts#like', as: 'like', defaults: { format: 'js' }
  post 'posts/id:id/dislike' => 'posts#dislike', as: 'dislike', defaults: { format: 'js' }
  
  post 'posts/id:id' => 'comments#create', as: 'new_comment', defaults: { format: 'js'}
  delete 'comments/id:id' => 'comments#destroy', as: 'comments'
  
  get 'search/quick' => 'search#quick', as: 'qsearch'
  get 'search/' => 'search#index', as: 'search'
  
  get 'follows' => 'users#follows', as: 'follows'
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Smileme
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    %header
      %nav
        - if user_signed_in?
          %input{type: "text", class: "search"}
          = link_to image_tag(asset_path("search-medium.png")), search_path
          = link_to image_tag(asset_path("home.png")), current_user
          = link_to image_tag(asset_path("logout.png")), destroy_user_session_path, method: :delete
        -else
          = link_to image_tag(asset_path("login.png")), user_session_path
          = link_to image_tag(asset_path("signup.png")), new_user_registration_path
    %main
      -if notice
        #notice
          %em.close ×
          =notice
      -if flash[:error]
        #error
          %em.close ×
          = flash[:error]
      = yield